
server:
   port: 8100
      
spring:
  application:
    name: ZuulGateway
    
zuul:
   routes:
   
      GUEST:
       url: http://localhost:9096  
       
      RESERVATION:
       url: http://localhost:9094
      
      PAYMENT:
       url: http://localhost:9093 
       
      STAFF:
       url: http://localhost:9097 
        
      BILL:
       url: http://localhost:9092  
       
      RECEPTIONIST:
       url: http://localhost:9011
       
      LOGIN:
      url : http://localhost:8006
       
       
      
                  
        
    
